spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: myschema
        dialect: org.hibernate.dialect.PostgreSQLDialect

dist:
  jar: chunk-upload-manager

server:
  port: 8080

output:
  temp: src/output/temp
  result: src/output/result